language: node_js
node_js:
- 15
before_install:
- npm install jest-cli --global
install:
- npm install
script:
- npm test
cache: npm
deploy:
  provider: heroku
  api_key:
    secure: bXhJuw+k/MUxl2YSnTcEn1YLbFm2XcVR3cADaiIKbvX3uoBq9l+T3gXAy9YfO694AiJ+GfFrQsTSCpHlvg4JUVUb8U+mWqvtPBF/surA1OdBFTAMKhDm/0reQt67MW3vhYc5Ki3mpmlWXQo+e+usu0GEmFu3hjVEt9laOz2YnaXP5DC2ARyoWQshH3UiybcTEhpK/jnOEYoakdXITeF4TVKYPcX/+OdgMSWbfMMvBeJZHjokNvn6990lOkBvLX4j8wnGLltNmJQ1y9ej9GGQnOtihcMkosXemLu95H3vOzZh9psD/MtIiJqD2kJhaCFOsmREDVvXoApyoy5f3R8pMYKEkpaQCBq/ZravdJWka6VtYlKHpd0yh+7JHqs8loU3kYXZQG774O+uRkQne3a7Y78uJ4X0zrsHIVHH+Fk8zBsF7AcQkmnIdAMQAOkmxFDumtkK39jBJ35wyYLYgxSJK9J/4iANsUWW0LARobNu3teQWELlINwuOSWcQpVznD/XiKPQsYk7sAtTFM9R1L52obnsyo9eaWq29bkB3r0opfdRHqPnysvfdbfeBlnSFkgMK2XqkZS5sAE0yZoV2sLnxEM5XvKtbrX2GrNvuHkbhSganAvgyZhih4VOHQ4ya/svcIIDkjdQQ041Vni7LlgI8HRLP0VL+2eIJeiLzVGAhGw=
  app:
    main: my-validation-api
